### ISSUE TITLE
:paginate-elements-by-height not working as expected

### ISSUE THREAD

**Issue by corazzi** [kempsteven/vue-html2pdf#44]
**Describe the bug**
I set `:manual-pagination="false"` and `:paginate-elements-by-height="700"` (for example).
The elements do not move onto the next page after the height limit is reached.

**To Reproduce**
Here is a condensed copy of my Vue component, containing just the settings I'm using and 4 x 250px high elements.

Because the `:paginate-elements-by-height` property is `700`, I would expect the third block to be on the next page as the total height for all 4 would be 1000px, and the total height for the first 3 to be 750px.

```html
<template>
    <VueHtml2Pdf
        ref="pdf"
        class="mx-auto"
        :float-layout="false"
        :enable-download="true"
        :preview-modal="false"
        :htmlToPdfOptions="htmlToPdfOptions"
        pdf-content-width="960px"
        :manual-pagination="false"
        :paginate-elements-by-height="700"
    >
        <template slot="pdf-content">
            <div style="height: 250px; background: red;"></div>
            <div style="height: 250px; background: blue;"></div>
            <div style="height: 250px; background: green;"></div>
            <div style="height: 250px; background: orange;"></div>
        </template>
    </VueHtml2Pdf>
</template>

<script>
import VueHtml2Pdf from 'vue-html2pdf';

export default {
    components: {
        VueHtml2Pdf,
    },

    data() {
        return {
            htmlToPdfOptions: {
                margin: 0.5,
                filename: 'PaginateByHeight.pdf',
                image: {
                    type: 'jpeg',
                    quality: 1
                },
                enableLinks: false,
                html2canvas: {
                    scale: 4,
                    scrollX: 0,
                    scrollY: 0,
                    useCORS: true,
                    width: 960,
                },
                jsPDF: {
                    unit: 'in',
                    format: 'a4',
                    orientation: 'portrait'
                }
            }
        };
    },

    mounted() {
        this.$refs.pdf.generatePdf();
    }
}
</script>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/915909/98921367-1f794600-24c9-11eb-81ab-f7f413ed3daf.png)

**Package Version**
1.8.0

**Additional context**
The actual PDF I'm generating is somewhat more complicated, with many charts, but each chart is still in its own section and they have very similar heights (+-50px). The charts are being cut off which is why I need the pagination by height functionality.

**Comment by kempsteven** [comment]
Okay I'll get back to you when I replicate the issue

**Comment by kempsteven** [comment]
Okay so I've replicated the issue, and I've also found a fix.

Using `<template>` on the slot affects the retrieval of elements inside the `pdf-content` slot, which makes the pagination fail.
You should use `<div>` or `<section>` or any other html element.

I also discovered that on the `htmlToPdfOptions.html2canvas`, the `width` property there messes up with the html2pdf.js's page breaks, it could be a bug in html2pdf.js package. you should remove the width property and just use css to achieve the style that you want.

**Comment by corazzi** [comment]
Sorry for the late reply @kempsteven but that was absolutely the issue and I managed to get it resolved with those changes. Thank you very much!

**Comment by kempsteven** [comment]
Cool, Glad to hear that!

**Comment by dev11-dccolorweb** [comment]
I'm still facing the issue with the html2Canvas "width" property, is still breaking the page split
